server:
  port: ${PROCUREMENT_SERVICE_PORT:8085}

spring:
  application:
    name: procurement-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
