server:
  port: ${CUSTOMER_LEDGER_SERVICE_PORT:8083}

spring:
  application:
    name: customer-ledger-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
