<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.rrjaggery</groupId>
        <artifactId>rr-jaggery-services</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>customer-ledger-service</artifactId>
    <packaging>jar</packaging>
    <name>Customer and Ledger Service</name>
    <description>Retail, B2B and Offline Wholesale Customer Ledgers</description>

    <dependencies>
        <dependency>
            <groupId>com.rrjaggery</groupId>
            <artifactId>common-library</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
